[tool.poetry]
name = "mail"
version = "0.1.0"
description = ""
authors = ["luis leal"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
